let piezas=[
    {
        "piece":"rook-white-piece","column":"A","row":"1",
        "classes":[
            {"class":"rook-white-piece"},
            {"class":"rook-piece"}
        ]
    },
    {
        "piece":"knight-white-piece","column":"B","row":"1",
        "classes":[
            {"class":"knight-white-piece"},
            {"class":"knight-piece"}
        ]
    },
    {
        "piece":"bishop-white-piece","column":"C","row":"1",
        "classes":[
            {"class":"bishop-white-piece"},
            {"class":"bishop-piece"}
        ]        
    },
    {
        "piece":"king-white-piece","column":"D","row":"1",
        "classes":[
            {"class":"king-white-piece"},
            {"class":"king-piece"}
        ]   
    },    
    {
        "piece":"queen-white-piece","column":"E","row":"1",
        "classes":[
            {"class":"queen-white-piece"},
            {"class":"queen-piece"}
        ] 
    },
    {
        "piece":"bishop-white-piece","column":"F","row":"1",
        "classes":[
            {"class":"bishop-white-piece"},
            {"class":"bishop-piece"}
        ] 
    },
    {
        "piece":"knight-white-piece","column":"G","row":"1",
        "classes":[
            {"class":"knight-white-piece"},
            {"class":"knight-piece"}
        ] 
    },
    {
        "piece":"rook-white-piece","column":"H","row":"1",
        "classes":[
            {"class":"rook-white-piece"},
            {"class":"rook-piece"}
        ] 
    },
    {
        "piece":"pawn-white-piece","column":"A","row":"2",
        "classes":[
            {"class":"pawn-white-piece"},
            {"class":"pawn-piece"}
        ] 
    },
    {
        "piece":"pawn-white-piece","column":"B","row":"2",
        "classes":[
            {"class":"pawn-white-piece"},
            {"class":"pawn-piece"}
        ] 
    },
    {
        "piece":"pawn-white-piece","column":"C","row":"2",
        "classes":[
            {"class":"pawn-white-piece"},
            {"class":"pawn-piece"}
        ] 
    },
    {
        "piece":"pawn-white-piece","column":"D","row":"2",
        "classes":[
            {"class":"pawn-white-piece"},
            {"class":"pawn-piece"}
        ] 
    },
    {
        "piece":"pawn-white-piece","column":"E","row":"2",
        "classes":[
            {"class":"pawn-white-piece"},
            {"class":"pawn-piece"}
        ] 
    },
    {
        "piece":"pawn-white-piece","column":"F","row":"2",
        "classes":[
            {"class":"pawn-white-piece"},
            {"class":"pawn-piece"}
        ] 
    },
    {
        "piece":"pawn-white-piece","column":"G","row":"2",
        "classes":[
            {"class":"pawn-white-piece"},
            {"class":"pawn-piece"}
        ] 
    },
    {
        "piece":"pawn-white-piece","column":"H","row":"2",
        "classes":[
            {"class":"pawn-white-piece"},
            {"class":"pawn-piece"}
        ] 
    },
    {
        "piece":"rook-black-piece","column":"A","row":"8",
        "classes":[
            {"class":"rook-black-piece"},
            {"class":"rook-piece"}
        ] 
    },
    {
        "piece":"knight-black-piece","column":"B","row":"8",
        "classes":[
            {"class":"knight-black-piece"},
            {"class":"knight-piece"}
        ] 
    },
    {
        "piece":"bishop-black-piece","column":"C","row":"8",
        "classes":[
            {"class":"bishop-black-piece"},
            {"class":"bishop-piece"}
        ] 
    },
    {
        "piece":"queen-black-piece","column":"D","row":"8",
        "classes":[
            {"class":"queen-black-piece"},
            {"class":"queen-piece"}
        ] 
    },
    {
        "piece":"king-black-piece","column":"E","row":"8",
        "classes":[
            {"class":"king-black-piece"},
            {"class":"king-piece"}
        ] 
    },
    {
        "piece":"bishop-black-piece","column":"F","row":"8",
        "classes":[
            {"class":"bishop-black-piece"},
            {"class":"bishop-piece"}
        ] 
    },
    {
        "piece":"knight-black-piece","column":"G","row":"8",
        "classes":[
            {"class":"knight-black-piece"},
            {"class":"knight-piece"}
        ] 
    },
    {
        "piece":"rook-black-piece","column":"H","row":"8",
        "classes":[
            {"class":"rook-black-piece"},
            {"class":"rook-piece"}
        ] 
    },
    {
        "piece":"pawn-black-piece","column":"A","row":"7",
        "classes":[
            {"class":"pawn-black-piece"},
            {"class":"pawn-piece"}
        ] 
    },
    {
        "piece":"pawn-black-piece","column":"B","row":"7",
        "classes":[
            {"class":"pawn-black-piece"},
            {"class":"pawn-piece"}
        ] 
    },
    {
        "piece":"pawn-black-piece","column":"C","row":"7",
        "classes":[
            {"class":"pawn-black-piece"},
            {"class":"pawn-piece"}
        ] 
    },
    {
        "piece":"pawn-black-piece","column":"D","row":"7",
        "classes":[
            {"class":"pawn-black-piece"},
            {"class":"pawn-piece"}
        ] 
    },
    {
        "piece":"pawn-black-piece","column":"E","row":"7",
        "classes":[
            {"class":"pawn-black-piece"},
            {"class":"pawn-piece"}
        ] 
    },
    {
        "piece":"pawn-black-piece","column":"F","row":"7",
        "classes":[
            {"class":"pawn-black-piece"},
            {"class":"pawn-piece"}
        ] 
    },
    {
        "piece":"pawn-black-piece","column":"G","row":"7",
        "classes":[
            {"class":"pawn-black-piece"},
            {"class":"pawn-piece"}
        ] 
    },
    {
        "piece":"pawn-black-piece","column":"H","row":"7",
        "classes":[
            {"class":"pawn-black-piece"},
            {"class":"pawn-piece"}
        ] 
    }
]
let PieceMovs=[
    {
        "piece":"pawn",
        "moves":[
            {
                "type":"vertical","distance":2
            },
            {
                "type":"diagonal","distance":1
            }
        ],
        "oriented":true
    },
    {
        "piece":"rook",
        "moves":[
            {
                "type":"vertical","distance":0
            },
            {
                "type":"horizontal","distance":0
            }
        ],
        "oriented":false
    },
    {
        "piece":"knight",
        "moves":[
            {
                "type":"ELLE","distance":0
            }
        ],
        "oriented":false
    },
    {
        "piece":"bishop",
        "moves":[
            {
                "type":"diagonal","distance":0
            }
        ],
        "oriented":false
    },
    {
        "piece":"queen",
        "moves":[
            {
                "type":"vertical","distance":0
            },
            {
                "type":"horizontal","distance":0
            },
            {
                "type":"diagonal","distance":0
            }
        ],
        "oriented":false
    },
    {
        "piece":"king",
        "moves":[
            {
                "type":"vertical","distance":1
            },
            {
                "type":"horizontal","distance":1
            },
            {
                "type":"diagonal","distance":1
            }
        ],
        "oriented":false
    }
]
let colors=[
    {   
        "name":"default",
        "white-tile-color": "#F1D8B6",
        "black-tile-color": "#B68864",
        "selected-white-tile-color": "#F5E7A5",
        "selected-black-tile-color": "#DAC333"
    },
    {   
        "name":"brown",
        "white-tile-color": "#dfe7ff",
        "black-tile-color": "#4a1ae8",
        "selected-white-tile-color": "#00FFFF",
        "selected-black-tile-color": "#00CED1"

    }
]